README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.3.3 Therefore, I updated the release notes in the readme file with the change made for this release and moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo.

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.4.5 Therefore, I updated the release notes in the readme file with the change made for this release and moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.4.6 release.

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.5.8 Therefore, I updated the release notes in the readme file with the change made for this release and moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.5.8 release

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.6.12 Therefore, I updated the release notes in the readme file with the change made for this release and moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.6.12 Release

README.md, package.json
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.7.11 Therefore, I moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.7.11 Release 

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.8.9 Therefore, I moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.8.9 Release

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.9.10 Therefore, I moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.9.10 Release

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.10.12. Therefore, I moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.10.12 Release

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.11.10. Therefore, I moved all the files from the private repository to the public one.|
=> Moved the private boldbi-sdk repo changes to Public repo for v6.11.10 Release 

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.12.12. Therefore, I moved all the files from the private repository to the public one.|
=> merge v6.12.12 changes 

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.13.11. Therefore, I moved all the files from the private repository to the public one.|
=> merge 6.13.11 changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.15.11. Therefore, I moved all the files from the private repository to the public one.|
=> merge 6.15.11 changes

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
|Solution description   |The bold BI release will be rolled out in version 6.16.12. Therefore, I moved all the files from the private repository to the public one.|
=> 335389 merge 6.16.12 changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |[TASK 337749](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/337749) Moved the release changes from the private repository to the public repository|
|Solution description   |The bold BI release will be rolled out in version 6.17.13. Therefore, I moved all the files from the private repository to the public one.|
=> 337749 merge 6.17.13 changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |[TASK 339854](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/339854) Moved the release changes from the private repository to the public repository|
|Solution description   |The bold BI release will be rolled out in version 6.18.11. Therefore, I moved all the files from the private repository to the public one.|
=> 339854 merge 6.18.11 changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |[TASK 342545](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/342545) Moved the release changes from the private repository to the public repository|
|Solution description   |The bold BI release will be rolled out in version 6.19. Therefore, I moved all the files from the private repository to the public one.|
=> merge-6.19-changes

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |[TASK 34](htt5278ps://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/345278) Moved the release changes from the private repository to the public repository|
|Solution description   |The bold BI release will be rolled out in version 6.19. Therefore, I moved all the files from the private repository to the public one.|
=> merge-7.1.16-changes

package.json
|||
|---|----|
| Task Description  |  https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/351737 Update the release version in the SDK file repo|
|Solution description   |The Bold BI release will be rolled out in version 7.4.11. Consequently, the embedded SDK version needs to be upgraded to 7.4.11. in the package.json file.|
=> merge-7.4.11-changes.

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |  https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/354599 Update the release version in the SDK file repo. |
|Solution description   |The bold BI release will be rolled out in version 7.5.13. Therefore, I moved all the files from the private repository to the public one.|
=> merge-7.5.13-changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |  https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/357443 Update the release version in the SDK file repo|
|Solution description   |The Bold BI release will be rolled out in version 7.6.12. Consequently, the embedded SDK version needs to be upgraded to 7.6.12. in the package.json file.|
=> merge-7.6.12-changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |  https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/359582 Post release works for Bold BI v7.7 release |
|Solution description   |The Bold BI release will be rolled out in version 7.7.9. Consequently, the embedded SDK version needs to be upgraded to 7.7.9. in the package.json file.|
=> merge-7.7.9-changes

README.md, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |  [Task 364015](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/364015): Post release works for Bold BI v7.8 release. |
|Solution description   |The Bold BI release will be rolled out in version 7.8.18. Consequently, the embedded SDK version needs to be upgraded to 7.8.18. in the package.json file.|
=> merge-7.8-changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  |  [Task 368964](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/368964): Post release works for Bold BI v7.9 release. |
|Solution description   |The Bold BI release will be rolled out in version 7.9.27. Consequently, the embedded SDK version needs to be upgraded to 7.9.27. in the package.json file.|
=> merge-7.9-changes

package.json
|||
|---|----|
| Task Description  |  [Task 368964](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/368964): Post release works for Bold BI v7.9 release. |
|Solution description   |The Bold BI release will be rolled out in version 7.9.50. Consequently, the embedded SDK version needs to be upgraded to 7.9.50. in the package.json file.|
=> merge-7.9.50-changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  | [Task 373615](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/373615): Pre and Post release work for v7.10. |
|Solution description   |The Bold BI release will be rolled out in version 7.10.16. Consequently, the embedded SDK version needs to be upgraded to 7.10.16. in the package.json file.|
=> merge-7.10-changes

README.md
Task link: https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/376545
=> 376545-Resolve-readme-file-issue-in-embedded-sdk

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
|||
|---|----|
| Task Description  | [Task 381218](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/381218): Pre and Post release work for v7.11|
|Solution description   |The Bold BI release will be rolled out in version 7.11.24. Consequently, the embedded SDK version needs to be upgraded to 7.11.24. in the package.json file.|
=> 381218 - merge-7.11-changes

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
[Task 392082](https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/392082): Pre and Post release work for v8.1
=> 392082: Pre and Post release work for v8.1

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
Done the post release works for v8,2
Task link: https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/397070
=> 397070 - Post release work for v8.2

README.md, dist/embeddingLocalization.js, dist/index.d.ts, dist/index.js, package.json, src/embeddingLocalization.ts, src/index.ts
Done the post release works for v9.1
Task link: https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/407112
=> 407112 - Post release work for v9.1

README.md, dist/index.d.ts, dist/index.js, package.json, src/index.ts
Done the post release works for v11.2
Task link: https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/420988
=> 420988 - Post release work for v11.2

package.json
Resolved dependent alerts of jquery version upgraded. Ensured in normal ASP.NET Core and Angular with ASP.NET Core samples.
Task link: https://dev.azure.com/Syncfusion-Bold/Bold-BI/_workitems/edit/435659
Screenshots:
=> Improvement(435659): Resolve dependent alert
